name: CI

on:
  pull_request:
    branches: [master, main]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -r requirements.txt
      - run: black --check .
      - run: pylint slack_bot/ --rcfile=.pylintrc

  pr-description-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Write PR body to file
        run: echo "${{ github.event.pull_request.body }}" > pr_body.txt
      - name: Check PR description format
        run: |
          pip install requests
          python .github/scripts/check_pr_description.py pr_body.txt

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -r requirements.txt
      - run: pytest tests